/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExemploPilha;

public class App {
    
    public static void main(String[] args) {
       int topo=0, num;
       
       Pilha p1 = new Pilha();
       
       num = p1.tamanho();
       
       System.out.println("O tamanho da Pilha eh..: "+num);
       System.out.println("------------------------------");
       
       p1.imprimir(topo);
       
       System.out.println("------------------------------");
       
       topo = p1.push(topo, 5);
       p1.imprimir(topo);
       
       System.out.println("------------------------------");
       
       topo = p1.push(topo, 7);
       p1.imprimir(topo);
       
       System.out.println("------------------------------");
       
       topo = p1.push(topo, 2);
       p1.imprimir(topo);
       
       System.out.println("------------------------------");
       
       topo = p1.push(topo, 3);
       p1.imprimir(topo);
       
       System.out.println("------------------------------");
       
       num = p1.top(topo);
       System.out.println("O valor no topo da pilha eh..: "+num);
       
       System.out.println("------------------------------");
       
       topo = p1.top(topo);
       
       num = p1.top(topo);
       System.out.println("O valor no topo da pilha eh..: "+num);
       
       p1.imprimir(topo);
       
       System.out.println("------------------------------");
       
       
    }
}
